CREATE TABLE `javatodo_admin` (
  `id` char(25) NOT NULL DEFAULT '',
  `mobile` varchar(25) NOT NULL DEFAULT '',
  `username` varchar(99) NOT NULL DEFAULT '',
  `password` char(32) NOT NULL DEFAULT '',
  `name` varchar(64) NOT NULL DEFAULT '',
  `alias` varchar(64) NOT NULL DEFAULT '',
  `hader_img` varchar(255) NOT NULL DEFAULT '',
  `department` text NOT NULL,
  `role_id` char(25) NOT NULL DEFAULT '0',
  `sort` int(11) NOT NULL DEFAULT '0',
  `position` varchar(128) NOT NULL DEFAULT '',
  `gender` tinyint(4) NOT NULL DEFAULT '1',
  `email` varchar(64) NOT NULL DEFAULT '',
  `biz_mail` varchar(64) NOT NULL DEFAULT '',
  `telephone` varchar(32) NOT NULL DEFAULT '',
  `is_leader_in_dept` text NOT NULL,
  `direct_leader` varchar(150) NOT NULL DEFAULT '',
  `external_position` varchar(36) NOT NULL DEFAULT '',
  `address` varchar(128) NOT NULL DEFAULT '',
  `main_department` char(25) NOT NULL DEFAULT '',
  `apptoken` varchar(99) DEFAULT '',
  `is_del` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4