CREATE TABLE `javatodo_category` (
  `id` char(25) NOT NULL DEFAULT '',
  `pid` char(25) NOT NULL DEFAULT '',
  `website_id` char(25) NOT NULL DEFAULT '',
  `type` varchar(25) NOT NULL ,
  `seo_title` varchar(255) NOT NULL DEFAULT '',
  `seo_keywords` varchar(255) NOT NULL DEFAULT '',
  `seo_description` varchar(255) NOT NULL DEFAULT '',
  `category_name` varchar(99) NOT NULL ,
  `category_sub_name` varchar(99) NOT NULL DEFAULT '' ,
  `pic` varchar(255) NOT NULL ,
  `url` varchar(255) NOT NULL DEFAULT '' ,
  `smalltext` text NOT NULL ,
  `detail` mediumtext NOT NULL ,
  `category_type` tinyint(4) NOT NULL DEFAULT '0' ,
  `pc_list_renovation_id` char(25) NOT NULL DEFAULT '',
  `mobile_list_renovation_id` char(25) NOT NULL DEFAULT '',
  `pc_page_renovation_id` char(25) NOT NULL DEFAULT '',
  `mobile_page_renovation_id` char(25) NOT NULL DEFAULT '',
  `pc_custom_id` char(25) NOT NULL DEFAULT '',
  `mobile_custom_id` char(25) NOT NULL DEFAULT '',
  `order_by` varchar(99) NOT NULL DEFAULT '',
  `is_hidden` tinyint(4) NOT NULL DEFAULT '0' ,
  `sort` int(11) NOT NULL DEFAULT '0' ,
  `is_del` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `website_id` (`website_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4