CREATE TABLE `javatodo_detail` (
  `id` char(25) NOT NULL DEFAULT '',
  `website_id` char(25) NOT NULL DEFAULT '',
  `admin_id` char(25) NOT NULL DEFAULT '' ,
  `type` varchar(99) NOT NULL DEFAULT '',
  `category_id` char(25) NOT NULL DEFAULT '' ,
  `url` varchar(255) NOT NULL DEFAULT '' ,
  `seo_title` varchar(255) NOT NULL ,
  `seo_keywords` varchar(255) NOT NULL ,
  `seo_description` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL ,
  `pic` varchar(255) NOT NULL ,
  `smalltext` text NOT NULL ,
  `release_time` bigint(20) NOT NULL ,
  `detail` mediumtext NOT NULL ,
  `sort` int(11) NOT NULL DEFAULT '0' ,
  `renovation_type` tinyint(4) NOT NULL DEFAULT '0' ,
  `pc_renovation_id` char(25) NOT NULL DEFAULT '' ,
  `pc_custom_id` char(25) NOT NULL DEFAULT '' ,
  `mobile_renovation_id` char(25) NOT NULL DEFAULT '' ,
  `mobile_custom_id` char(25) NOT NULL DEFAULT '' ,
  `views` int(11) NOT NULL ,
  `recommend_level` tinyint(4) NOT NULL DEFAULT '0' ,
  `is_del` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `website_id` (`website_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4