CREATE TABLE `javatodo_goods` (
  `goods_id` varchar(25) NOT NULL ,
  `goods_name` varchar(255) NOT NULL ,
  `goods_pic` varchar(255) NOT NULL ,
  `goods_sign` varchar(99) NOT NULL ,
  `category_name` varchar(99) NOT NULL ,
  `mall_name` varchar(99) NOT NULL ,
  `mall_id` varchar(25) NOT NULL ,
  `brand_name` varchar(25) NOT NULL ,
  `promotion_rate` float NOT NULL ,
  `promotion_money` decimal(10,2) NOT NULL ,
  `sales_tip` varchar(25) NOT NULL ,
  `original_price` decimal(10,2) NOT NULL ,
  `coupon_discount` decimal(10,2) NOT NULL ,
  `price` decimal(10,2) NOT NULL ,
  `search_id` varchar(99) NOT NULL ,
  `platform` varchar(25) NOT NULL ,
  `cat1` varchar(99) NOT NULL,
  `cat2` varchar(99) NOT NULL,
  `cat3` varchar(99) NOT NULL,
  `url` varchar(255) NOT NULL,
  `banner` text NOT NULL,
  `goods_detail` text NOT NULL,
  `coupon_url` varchar(255) NOT NULL,
  PRIMARY KEY (`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4