CREATE TABLE `javatodo_union_order` (
  `id` char(25) NOT NULL DEFAULT '',
  `order_sn` varchar(99) NOT NULL DEFAULT '',
  `pay_time` bigint(20) NOT NULL ,
  `type` varchar(25) NOT NULL DEFAULT '',
  `status` tinyint(4) NOT NULL DEFAULT '0' ,
  `order_money` decimal(10,2) NOT NULL DEFAULT '0.00',
  `commission` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `uid` char(25) NOT NULL DEFAULT '',
  `level_1_id` char(25) NOT NULL DEFAULT '',
  `level_1_money` decimal(10,2) NOT NULL DEFAULT '0.00',
  `level_2_id` char(25) NOT NULL DEFAULT '',
  `level_2_money` decimal(10,2) NOT NULL DEFAULT '0.00',
  `level_3_id` char(25) NOT NULL DEFAULT '',
  `level_3_money` decimal(10,2) NOT NULL DEFAULT '0.00',
  `platform_money` decimal(10,2) NOT NULL ,
  `note` varchar(255) NOT NULL DEFAULT '' ,
  `is_add_into_money_log` tinyint(4) NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `order_sn` (`order_sn`),
  KEY `status` (`status`),
  KEY `type` (`type`),
  KEY `pay_time` (`pay_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4